force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdopterQueriesTest.cls
@IsTest
public with sharing class AdopterQueriesTest {
    @TestSetup
    static void makeData(){
        List<Adopter__c> adopterList = TestDataFactory.createAdotperList(10);
        insert adopterList;
        List<Animal__c> animalList = TestDataFactory.createAnimalList(10);
        insert animalList;
    }

    @IsTest
    public static void getAdopterInformationByIdTest() {
        Adopter__c adopter = [
            SELECT Id
            FROM Adopter__c
            WITH SYSTEM_MODE
            LIMIT 1
        ];
        Test.startTest();
        Adopter__c adopterInfo = AdopterQueries.getAdopterInformationById(adopter.Id);
        Test.stopTest();
        System.assertEquals(adopter.Id, adopterInfo.Id, 'It\'s been retrieved a wrong animal.');
    }

    @IsTest
    public static void getAdopterInformationByNullIdTest() {
        String errorMessage;
        Test.startTest();
        try {
            Adopter__c adopterInfo = AdopterQueries.getAdopterInformationById(null);
        } catch (System.NullPointerException e) {
            errorMessage = e.getMessage();
        }
        System.assert(errorMessage != null, 'It should be null.');
    }
    
    @IsTest
    public static void getAvailableAdopterListTest() {
        Map<String, AdopterQueries.FieldProperty> adopterPropertyMap;
        String errorMessage;
        Test.startTest();
        try {
            adopterPropertyMap = AdopterQueries.getAvailableAdopterList();
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        Test.stopTest();
        System.debug('YNASC errorMessage: '+errorMessage);
        System.assertEquals(10, adopterPropertyMap.size(), 'It should not be null.');
    }
}