force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetAdopterInfoTest.cls
@IsTest
public with sharing class GetAdopterInfoTest {

    @TestSetup
    static void makeData(){
        Animal__c animal = new Animal__c(Name = 'Pimpolho');
        insert animal;

        Adopter__c adopter = new Adopter__c(Name = 'Juliano');
        insert adopter;

        Adoption__c adoption = new Adoption__c(
            Animal__c = animal.Id,
            Adopter__c = adopter.Id
        );
        insert adoption;
    }

    @IsTest
    public static void getAdopterIdTest() {
        Animal__c animal = [
            SELECT Id
            FROM Animal__c
            WITH USER_MODE
            LIMIT 1
        ];
        Adopter__c adopter = [
            SELECT Id
            FROM Adopter__c
            WITH USER_MODE
            LIMIT 1
        ];
        Adoption__c adoption = [
            SELECT Id, Adopter__r.Id, Adopter__r.Name
            FROM Adoption__c
            WHERE Animal__c = :animal.Id
            WITH USER_MODE
            LIMIT 1
        ];

        Test.startTest();
        Map<String, String> adopterMapInfo = GetAdopterInformation.getAdopterIdFromAdoption(animal.Id);
        Test.stopTest();
        String adopterId = new List<String> (adopterMapInfo.keySet()).get(0);
        
        System.assertEquals(String.valueOf(adopter.Id), adopterId, 'Adoption don\'t match to the right Adopter');
    }
}