force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnimalTriggerHelperTest.cls
@IsTest
public with sharing class AnimalTriggerHelperTest {
    @TestVisible
    private static Integer numberOfRecords = 10;
    
    @TestSetup
    static void makeData(){
        List<Adopter__c> adopterList = TestDataFactory.createAdotperList(numberOfRecords);
        insert adopterList;
        List<Animal__c> animalList = TestDataFactory.createAnimalList(numberOfRecords);
        insert animalList;
        List<Adoption__c> adoptionList = TestDataFactory.createAdoptionList(adopterList, animalList);
        insert adoptionList;
    }

    @Istest
    public static void beforeAfterInsert() {
        Animal__c animal = new Animal__c(Name = 'Test before after');
        Test.startTest();
        insert animal;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AnimalTriggerHelperTest.beforeAfterInsert');
        System.assert(true, 'Create insert Test.');
    }

    @Istest
    public static void beforeAfterUpdate() {
        Animal__c animal = [
            SELECT Id, Name
            FROM Animal__c
            LIMIT 1
        ];
        animal.Name = 'test update';
        Test.startTest();
        update animal;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AnimalTriggerHelperTest.beforeAfterUpdate');
        System.assert(true, 'Create update Test.');
    }

    @Istest
    public static void beforeAfterDelete() {
        Animal__c animal = [
            SELECT Id, Name
            FROM Animal__c
            LIMIT 1
        ];
        Test.startTest();
        delete animal;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AnimalTriggerHelperTest.beforeAfterDelete');
        System.assert(true, 'Create delete Test.');
    }

    @Istest
    public static void afterUndelete() {
        Animal__c animal = [
            SELECT Id, Name
            FROM Animal__c
            LIMIT 1
        ];
        delete animal;
        Animal__c animalToUndelete = [
            SELECT Id, Name
            FROM Animal__c
            WHERE Id = :animal.Id
            LIMIT 1
            ALL ROWS
        ];
        Test.startTest();
        undelete animalToUndelete;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AnimalTriggerHelperTest.afterUndeleteTest');
        System.assert(true, 'Create undelete Test.');
    }
}