force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Adoption_Stage__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Stage__c</fullName>
    <description>Specifies whether the animal is in the process of adoption, has been adopted, or has been returned by the adopter.</description>
    <label>Adoption Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back to Shelter</fullName>
            </value>
            <value>
                <fullName>Adoption Process</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdoptionQueriesTest.cls
@IsTest
public with sharing class AdoptionQueriesTest {
    
    @TestVisible
    private static Integer numberOfRecords = 10;
    
    @TestSetup
    static void makeData(){
        List<Adopter__c> adopterList = TestDataFactory.createAdotperList(numberOfRecords);
        insert adopterList;
        List<Animal__c> animalList = TestDataFactory.createAnimalList(numberOfRecords);
        insert animalList;
        List<Adoption__c> adoptionList = TestDataFactory.createAdoptionList(adopterList, animalList);
        insert adoptionList;
    }

    @isTest
    public static void retrieveAdoptionStageInfoTest() {

        Test.startTest();
        Map<String, String> adoptionStagesMap = AdoptionQueries.retrieveAdoptionStageInfo();
        Test.stopTest();

        schema.DescribeFieldResult adoptionStages = schema.SObjectType.Adoption__c.fields.Adoption_Stage__c.getsObjectField().getDescribe();
        Map<String, String> adoptionStagesMapToCompare = new Map<String, String>();
        for (PicklistEntry ent : adoptionStages.getPicklistValues()) {
            if (ent.isActive()) {
                if (ent.getValue() == 'Adopted' || ent.getValue() == 'Adoption Process' || ent.getValue() == 'Back To Shelter') {
                    adoptionStagesMapToCompare.put(ent.getLabel(), ent.getValue());
                }
            }
        }
        System.assertEquals(adoptionStagesMapToCompare.get('Adopted'), adoptionStagesMap.get('Adopted'), 'It\'s not retrieving the Adopter option');
        System.assertEquals(adoptionStagesMapToCompare.get('Adoption Process'), adoptionStagesMap.get('Adoption Process'), 'It\'s not retrieving the Adoption Process option');
        System.assertEquals(adoptionStagesMapToCompare.get('Back To Shelter'), adoptionStagesMap.get('Back To Shelter'), 'It\'s not retrieving the Back To Shelter option');
        System.assertEquals(adoptionStagesMapToCompare.size(), adoptionStagesMap.size(), 'The number of options varies. One or more options have been added or deleted. Please ensure they are included in the tests.');
    }
}