force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Adoption_Stage__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Stage__c</fullName>
    <description>Specifies whether the animal is in the process of adoption, has been adopted, or has been returned by the adopter.</description>
    <label>Adoption Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back to Shelter</fullName>
            </value>
            <value>
                <fullName>Adoption Process</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/*
    * @author : Yan Nascimento
    * @Date : 2024/03/26
    * @Description : creates records for testing purposes.
    * @log : 2024/03/22 - created
*/
@IsTest
public with sharing class TestDataFactory {

    public static List<Adopter__c> createAdotperList(Integer numberOfAdopters) {
        List<Adopter__c> adopterList = new List<Adopter__c>();
        for (Integer i = 0; i < numberOfAdopters; i++) {
            Adopter__c adopter = new Adopter__c();
            adopter.Name = 'Aldo ' + i;
            adopterList.add(adopter);
        }
        return adopterList;
    }
    public static List<Animal__c> createAnimalList(Integer numberOfAnimals) {
        List<Animal__c> animalList = new List<Animal__c>();
        for (Integer i = 0; i < numberOfAnimals; i++) {
            Animal__c animal = new Animal__c();
            animal.Name = 'Lucas '+ i;
            animalList.add(animal);
        }
        return animalList;
    }
    public static List<Adoption__c> createAdoptionList(List<Adopter__c> adopterList, List<Animal__c> animalList) {
        List<Adoption__c> adoptionList = new List<Adoption__c>();
            for (Integer i = 0; i < adopterList.Size(); i++) {
                Adoption__c adoption = new Adoption__c();
                adoption.Animal__c = animalList[i].Id;
                adoption.Adopter__c = adopterList[i].Id;
                if (Math.mod(i, 2) == 0) {
                    adoption.Adoption_Stage__c = 'Adopted';
                } else {
                    adoption.Adoption_Stage__c = 'Adoption Process';
                }
                adoptionList.add(adoption);
            }
            return adoptionList;
    }
}