force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Adoption_Stage__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Stage__c</fullName>
    <description>Specifies whether the animal is in the process of adoption, has been adopted, or has been returned by the adopter.</description>
    <label>Adoption Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back to Shelter</fullName>
            </value>
            <value>
                <fullName>Adoption Process</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdoptionServices.cls
public with sharing class AdoptionServices {

    // Create an adoption only if the animal does not already have an adopter.
    @AuraEnabled (cacheable = false)
    public static Id createAdoption(Map<String, String> params) {
        Adoption__c newAdoption = new Adoption__c(
            Animal__c = params.get('animalId'),
            Adopter__c = params.get('adopterId'),
            Adoption_Stage__c = params.get('adoptionStage')
        );
        Animal__c animal = [
            SELECT Adopter__c
            FROM Animal__c
            WHERE Id = :newAdoption.Animal__c
            WITH SYSTEM_MODE
        ];
        if (Schema.sObjectType.Adoption__c.isCreateable() && animal.Adopter__c == null) {
            try {
                insert newAdoption;
            } catch (DmlException e) {
                System.debug('Error Message: '+e.getMessage());
                throw new DmlException('Error Message: '+e.getMessage());
            }
        } else {
            throw new DmlException('Permission denied to update, or the animal already has an adopter.');
        }
        return newAdoption.Id;
    }
}