force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Adopter__c.field-meta.xml
<CustomField>
    <fullName>Adopter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It can be assigned only programmatically after creating an adoption.</description>
    <inlineHelpText>It can be assigned only programmatically after creating an adoption.</inlineHelpText>
    <label>Adopter</label>
    <referenceTo>Adopter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdopterTriggerHandlerTest.cls
@IsTest
public with sharing class AdopterTriggerHandlerTest {

    @TestVisible
    private static Integer numberOfRecords = 10;

    @TestSetup
    static void makeData(){
        List<Adopter__c> adopterList = TestDataFactory.createAdotperList(numberOfRecords);
        insert adopterList;
        List<Animal__c> animalList = TestDataFactory.createAnimalList(numberOfRecords);
        insert animalList;
    }

    @isTest
    public static void beforeAfterInsertTest() {
        Adopter__c adopter = new Adopter__c(Name = 'John');
        Test.startTest();
        insert adopter;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AdopterTriggerHandlerTest.beforeAfterInsertTest');
        System.assert(true, 'Any code written.');
    }
    
    @isTest
    public static void beforeAfterUpdateTest() {
        Adopter__c adopter = [
            SELECT Id, Name
            FROM Adopter__c
            WITH SYSTEM_MODE
            LIMIT 1
            ];
        adopter.Name = 'Ambroglio';
        Test.startTest();
        update adopter;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AdopterTriggerHandlerTest.beforeAfterUpdateTest');
        System.assert(true, 'Any code written.');
    }

    @isTest
    public static void beforeAfterDeleteTest() {
        Adopter__c adopter = [
            SELECT Id, Name
            FROM Adopter__c
            WITH SYSTEM_MODE
            LIMIT 1
        ];
        Test.startTest();
        delete adopter;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AdopterTriggerHandlerTest.beforeAfterDeleteTest');
        System.assert(true, 'Any code written.');
    }

    @isTest
    public static void afterUndeleteTest() {
        Adopter__c adopter = [
            SELECT Id, Name
            FROM Adopter__c
            WITH SYSTEM_MODE
            LIMIT 1
        ];
        delete adopter;
        Adopter__c adopterToUndelete = [
            SELECT Id, Name
            FROM Adopter__c
            WHERE Id = :adopter.Id
            WITH SYSTEM_MODE
            LIMIT 1
            ALL ROWS
        ];
        Test.startTest();
        undelete adopterToUndelete;
        Test.stopTest();
        System.debug('YNASC - Review This Test Class: AdopterTriggerHandlerTest.afterUndeleteTest');
        System.assert(true, 'Any code written.');
    }
}