force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GetAdopter2Information.cls
public with sharing class GetAdopter2Information {

    //get Adopter Id from adoptions to Animal GetAdopter2Information.getAdopter2IdFromAdoption
    public void getAdopter2IdFromAdoption(Id animalId) {

        List<Adoption__c> adoption = [
            SELECT Id
            FROM Adoption__c
            WHERE Animal__c = :animalId
            WITH USER_MODE
        ];

        System.debug('Adoption Size: '+adoption.Size());
    }
}