force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adoption_Stage__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Stage__c</fullName>
    <description>Specifies whether the animal is in the process of adoption, has been adopted, or has been returned by the adopter.</description>
    <label>Adoption Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back to Shelter</fullName>
            </value>
            <value>
                <fullName>Adoption Process</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdoptionTriggerHelper.cls
public with sharing class AdoptionTriggerHelper {

    //check if the animal has been adopted by someone.
    public static void checkAnimalHasBeenAdopted(List<Adoption__c> newAdoptionList) {
        System.debug('YNASC newAdoptionList: '+newAdoptionList);
        Set<Id> animalIds = new Set<Id>();
        for (Adoption__c newAdoption : newAdoptionList) {
            Id animalId = newAdoption.Animal__c;
            animalIds.add(animalId);
        }
        List<Adoption__c> adoptedList = [
            SELECT Id, Animal__c,Adoption_Stage__c
            FROM Adoption__c
            WHERE Animal__c IN :animalIds AND Adoption_Stage__c = 'Adopted'
            WITH SYSTEM_MODE
        ];

        List<Adoption__c> adoptionInProcessList = [
            SELECT Id, Animal__c,Adoption_Stage__c
            FROM Adoption__c
            WHERE Animal__c IN :animalIds AND Adoption_Stage__c = 'Adoption Process'
            WITH SYSTEM_MODE
        ];

        if (!adoptedList.isEmpty()) {
            for (Adoption__c adoption : newAdoptionList) {
                adoption.Animal__c.addError('This animal has been adopted! Sorry!');
            }
        }

        if (!adoptionInProcessList.isEmpty()) {
            for (Adoption__c adoption : newAdoptionList) {
                adoption.Animal__c.addError('This animal is in adoption process! Sorry!');
            }
        }

    }
    public static void getAnimalId(Id adoptionId) {
        System.debug('');
    }
}