force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adoption_Stage__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Stage__c</fullName>
    <description>Specifies whether the animal is in the process of adoption, has been adopted, or has been returned by the adopter.</description>
    <label>Adoption Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back to Shelter</fullName>
            </value>
            <value>
                <fullName>Adoption Process</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdoptionQueries.cls
/*
    * @author : Yan Nascimento
    * @Date : 2024/04/30
    * @Description : centralized class to created Adoption Queries.
    * @log : 2024/04/30 - created
*/
public with sharing class AdoptionQueries {

    @AuraEnabled (cacheable = true)
    public static Map<String, String> retrieveAdoptionStageInfo(){
        schema.DescribeFieldResult adoptionStages = schema.SObjectType.Adoption__c.fields.Adoption_Stage__c.getsObjectField().getDescribe();
        Map<String, String> adoptionStagesMap = new Map<String, String>();
        for (PicklistEntry ent : adoptionStages.getPicklistValues()) {
            if (ent.isActive()) {
                adoptionStagesMap.put(ent.getLabel(), ent.getValue());
            }
        }
        return adoptionStagesMap;
    }
}