force-app/main/default/objects/Adopter2__c/Adopter2__c.object-meta.xml
<CustomObject>
    <label>Adopter2</label>
    <nameField>
        <label>Adopter2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>ADT-{0000}</displayFormat>
        <label>Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Adopter2__c.field-meta.xml
<CustomField>
    <fullName>Adopter2__c</fullName>
    <label>Adopter2</label>
    <referenceTo>Adopter2__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GetAdopter2InformationTest.cls
/*
    * @author : Yan Nascimento
    * @Date : 2024/03/21
    * @Description : test the GetAdopter2Information class
    * @log : 2024/03/21 - created
*/

@isTest
public with sharing class GetAdopter2InformationTest {

    @TestSetup
    static void makeData(){
        Animal__c animal = new Animal__c(Name = 'Pimpolho');
        insert animal;

        // Adopter2__c adopter = new Adopter2__c(Name = 'Juliano');
        // insert adopter;

        // Adoption__c adoption = new Adoption__c(
        //     Animal__c = animal.Id,
        //     Adopter2__c = adopter.Id
        // );
    }

    @isTest
    public static void getAdopter2InfoTest() {
        Animal__c animal = [
            SELECT Id
            FROM Animal__c
            LIMIT 1
        ];
        // Adoption__c adoption = [
        //     SELECT Id, Adopter2__c.Name
        //     FROM Adoption__c
        //     WHERE Animal__c.Id = :animal.Id
        // ];

        System.assert(true, true);
    }
}